fix launch failure when game has no Main.Args
imLinguin/nile pull request #25
Opened 2023-05-09 01:52 UTC by suchipi

this fixes a bug where the launch command fails if the game doesn't have `Main.Args` present (which is the case with Titan Souls, ID: 353f3a18-8bcf-48d5-8b78-3b37d9a136ce)

2023-05-09 07:09 UTC, imLinguin requested changes
Thanks for contributing! Could you apply this small change I commented on? This will make it more readable imo

2023-05-09 07:09 UTC, imLinguin commented on nile/utils/launch.py
> +            instruction.arguments = []
This can be replaced by this one liner
```
instruction.arguments = json_data["Main"].get("Args") or list()
```

2023-05-10 03:47 UTC, suchipi commented
done; thanks! I don't do much python, so I appreciate the tip :)

2023-05-10 08:51 UTC, imLinguin approved these changes
Once again, thanks!

2023-05-10 08:51 UTC, merged